# Generated by Django 3.1.3 on 2020-11-23 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
